[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
benchmark-simple = "0.1.7"

[dependencies]
lazy_static = "1.4.0"
regex = "1.11.1"
phf = "0.11.2"
rayon = "1.10.0"

[profile.test]
#opt-level = 3

